runtime: nodejs18

env_variables:
  DB_HOST : YOUR_HOST_DB
  DB_USER : YOUR_USER_DB
  DB_PASSWORD : YOUR_PASSWORD_DB
  DB_NAME : YOUR_DB_NAME
  JWT_SECRET : YOUR_JWT_SECRET


instance_class: F2

automatic_scaling:
  max_instances: 1

handlers:
- url: /.*
  script: auto
